FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY packages/shared/package.json packages/shared/package.json
COPY frontend/package.json frontend/package.json

RUN pnpm install

COPY packages/shared packages/shared
COPY frontend frontend

WORKDIR /app/frontend

EXPOSE 3000

CMD ["pnpm", "dev"]